[color-theme]
name = "Darcula"

[ui]
font-family = ""
font-size = 13
header-height = 35
status-height = 25
tab-min-width = 100
activity-width = 50
scroll-width = 10
drop-shadow-width = 0

[color-theme.base]
white = "#e4e4e4"
black = "#cccccc"
grey = "#707070"
blue = "#7A9EC2"
red = "#ff7373"
yellow = "#FFC66D"
orange = "#CC8242"
green = "#6A8759"
purple = "#9E7BB0"
cyan = "#7ab3c2"
magenta = "#b079ab"

[color-theme.syntax]
"attribute" = "$yellow"
"builtinAttribute" = "$yellow"
"builtinType" = "$blue"
"comment" = "#707070"
"constant" = "$purple"
"constructor" = "$yellow"
"embedded" = "$black"
"enum" = "$blue"
"enum-member" = "$blue"
"enumMember" = "$blue"
"escape" = "$black"
"field" = "$purple"
"function" = "$yellow"
"function.method" = "$yellow"
"interface" = "$blue"
"keyword" = "$orange"
"keyword.control" = "$orange"
"method" = "$yellow"
"number" = "$blue"
"property" = "$purple"
"selfKeyword" = "$orange"
"selfTypeKeyword" = "$orange"
"string" = "$green"
"string.escape" = "$green"
"string.macro" = "$green"
"string.template" = "$green"
"struct" = "$blue"
"structure" = "$blue"
"symbol" = "$black"
"type" = "$blue"
"type.builtin" = "$blue"
"typeAlias" = "$blue"
"lifetime" = "$orange"
"variable" = "$purple"
"parameter" = "$purple"
"boolean" = "$orange"
"macro" = "$yellow"
"formatSpecifier" = "$purple"
"derive" = "$blue"
"deriveHelper" = "$yellow"
"decorator" = "$yellow"
"namespace" = "$blue"
"generic.attribute" = "$yellow"
"unresolvedReference" = "$yellow"
"typeParameter" = "$blue"

[color-theme.ui]
"activity.background" = "$red"
"activity.current" = "$blue"
"completion.background" = "#242424"
"completion.current" = "#ffffff0b"
"completion_lens.foreground" = "#909090"
"editor.background" = "#242424"
"editor.caret" = "$black"
"editor.current_line" = "#ffffff0b"
"editor.dim" = "#909090"
"editor.drag_drop_background" = "#204182cc"
"editor.drag_drop_tab_background" = "#204182cc"
"editor.focus" = "$black"
"editor.foreground" = "$black"
"editor.indent_guide" = "#8080805b"
"editor.link" = "$blue"
"editor.selection" = "#204182cc"
"editor.sticky_header_background" = "#242424"
"editor.visible_whitespace" = "#242424"
"error_lens.error.background" = "#ffffff0b"
"error_lens.error.foreground" = "$red"
"error_lens.other.background" = "ffffff0b"
"error_lens.other.foreground" = "#909090"
"error_lens.warning.background" = "#ffffff0b"
"error_lens.warning.foreground" = "$yellow"
"hover.background" = "#242424"
"inlay_hint.background" = "#ffffff0b"
"inlay_hint.foreground" = "#909090"
"lapce.border" = "#ffffff1a"
"lapce.button.primary.background" = "$blue"
"lapce.button.primary.foreground" = "#000000"
"lapce.dropdown_shadow" = "#0000005b"
"lapce.error" = "$red"
"lapce.icon.active" = "#ffffff"
"lapce.icon.inactive" = "#707070"
"lapce.plugin.author" = "$black"
"lapce.plugin.description" = "$black"
"lapce.plugin.name" = "#e4e4e4"
"lapce.remote.connected" = "$green"
"lapce.remote.connecting" = "$yellow"
"lapce.remote.disconnected" = "$red"
"lapce.remote.icon" = "000000"
"lapce.remote.local" = "$blue"
"lapce.scroll_bar" = "#444444"
"lapce.tab.active.background" = "#ffffff1a"
"lapce.tab.active.foreground" = "#ffffff"
"lapce.tab.active.underline" = "#808080"
"lapce.tab.inactive.background" = "#2e2e2f"
"lapce.tab.inactive.foreground" = "$black"
"lapce.tab.inactive.underline" = "#252526"
"lapce.tab.separator" = "#252526"
"lapce.warn" = "$yellow"
"markdown.blockquote" = "#898989"
"palette.background" = "#323233"
"palette.current.background" = "#ffffff18"
"palette.current.foreground" = "#ffffff"
"palette.foreground" = "$black"
"panel.background" = "#323233"
"panel.current.background" = "#ffffff18"
"panel.current.foreground" = "#ffffff"
"panel.current.foreground.dim" = "$black"
"panel.foreground" = "$black"
"panel.foreground.dim" = "#c0bfbc"
"panel.hovered.background" = "#ffffff18"
"panel.hovered.foreground" = "#ffffff"
"panel.hovered.foreground.dim" = "$black"
"source_control.added" = "$green"
"source_control.modified" = "$blue"
"source_control.removed" = "$red"
"status.background" = "#3b3b3c"
"status.foreground" = "#cccccc"
"status.modal.insert" = "$red"
"status.modal.insert.background" = "$red"
"status.modal.insert.foreground" = "$black"
"status.modal.normal" = "$blue"
"status.modal.normal.background" = "$blue"
"status.modal.normal.foreground" = "$black"
"status.modal.terminal" = "$purple"
"status.modal.terminal.background" = "$purple"
"status.modal.terminal.foreground" = "$black"
"status.modal.visual" = "$yellow"
"status.modal.visual.background" = "$yellow"
"status.modal.visual.foreground" = "$black"
"terminal.background" = "#242424"
"terminal.black" = "$black"
"terminal.blue" = "$blue"
"terminal.bright_black" = "#585858"
"terminal.bright_blue" = "$blue"
"terminal.bright_cyan" = "$cyan"
"terminal.bright_green" = "$green"
"terminal.bright_magenta" = "$magenta"
"terminal.bright_red" = "$red"
"terminal.bright_white" = "$white"
"terminal.bright_yellow" = "$yellow"
"terminal.cursor" = "$white"
"terminal.cyan" = "$cyan"
"terminal.foreground" = "$white"
"terminal.green" = "$green"
"terminal.magenta" = "$magenta"
"terminal.red" = "$red"
"terminal.white" = "$white"
"terminal.yellow" = "$yellow"
